config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :places, only: [:index, :show] do
        member do
          get 'bookings/:on_day' => 'places#bookings', as: :bookings
        end
      end

      resources :bookings, only: [:create, :index]
      resources :ratings, only: [:create] do
        get 'current/:place_id/:user_id', :on => :collection, :action => 'show'
      end

      post 'login' => 'users#login', as: 'login'
      post 'logout' => 'users#logout', as: 'logout'
      post 'signup' => 'users#signup', as: 'signup'
      post '/users/profile' => 'users#update', as: 'update'
    end
  end

  devise_for :users, controllers: { sessions: 'sessions', passwords: 'passwords' }

  scope '/admin' do
    devise_for :admins

    resources :users
    resources :places, concerns: :paginatable do
      with_options except: [:index, :show] do |list_except|
        list_except.resources :schedules
        list_except.resources :services
      end
    end

    resources :bookings, only: [:index] do
      member do
        post 'approve'
        post 'discard'
      end

      collection do
        get 'canceled' => 'bookings#canceled', as: :canceled
        get 'approved' => 'bookings#approved', as: :approved
      end
    end
  end

  mount PostgresqlLoStreamer::Engine => '/lo'

  root 'places#index'
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  place_id     :integer
#  date         :datetime
#  created_at   :datetime
#  updated_at   :datetime
#  confirmed_at :datetime
#  canceled_at  :datetime
#

##
# Esta clase representa una reserva
# @author Jenny Lopez
class Booking < ActiveRecord::Base
  # Pertenece a
  belongs_to :place

  # Pertenece a
  belongs_to :user

  # Tiene varios servicios reservados
  has_many :booked_services

  # método para obtener reservas por confirmar
  scope :pending_confirm, (lambda do
    includes(:place, :user, :booked_services)
    .where(confirmed_at: nil, canceled_at: nil)
    .order(:date)
  end)

  # método para obtener reservas canceladas
  scope :canceled, (lambda do
    where.not(canceled_at: nil).order(:date)
  end)

  # método para obtener reservas aprovadas/confirmadas
  scope :approved, (lambda do
    where.not(confirmed_at: nil).order(:date)
  end)

  # método para obtener las reservas de un día en especifico
  scope :on_day, (lambda do |day|
    where(date: day.beginning_of_day..day.end_of_day).includes(:booked_services)
  end)

  # validaciones
  validates :booked_services, presence: true
  validates :place, presence: true
  validates :user, presence: true
  validates :date, presence: true

  # método que crea una nueva reserva y adiciona los servicios seleccionados
  # por el usuario
  def self.new_with_params(booking_params)
    services = booking_params.delete(:services)
    booking = Booking.new(booking_params)

    Service.where(id: services).each do |s|
      booking.booked_services.build(
        service_name: s.name,
        service_duration: s.duration
      )
    end

    booking
  end
end

app/controllers/api/v1/bookings_controller.rb
module API
  module V1
    ##
    # Esta clase representa un punto de montaje en el api para generar
    # una reserva
    class BookingsController < API::V1::BaseController
      doorkeeper_for :all

      def create
        booking = Booking.new_with_params(booking_params)

        if booking.save
          render json: booking.to_json(include: :booked_services), status: 200
        else
          render json: { errors: booking.errors }, status: 404
        end
      end

      def index
        @user = current_resource_owner

        included_relations = [:place, :user, :booked_services]
        @pending = @user.bookings.includes(*included_relations)

        render json: bookings.to_json(*included_relations), status: 200
      end

      private

      def booking_params
        params.permit(:place_id, :user_id, :date, services: [])
      end
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.pending_confirm
    @filtered_by = t(:pending_bookings)
  end

  def canceled
    @bookings = Booking.canceled
    @filtered_by = t(:canceled_bookings)
    render 'index'
  end

  def approved
    @bookings = Booking.approved
    @filtered_by = t(:approved_bookings)
    render 'index'
  end

  def approve
    booking = Booking.find(params[:id])
    if booking.update_attribute(:confirmed_at, DateTime.now)
      BookingMailer.approve_notification(booking.id).deliver
      flash[:success] = t(:booking_approved)
    else
      flash[:error] = t(:booking_not_approved)
    end
    redirect_to bookings_path
  end

  def discard
    booking = Booking.find(params[:id])
    if booking.update_attribute(:canceled_at, DateTime.now)
      BookingMailer.cancel_notification(booking.id).deliver
      flash[:success] = t(:booking_canceled)
    else
      flash[:error] = t(:booking_not_canceled)
    end
    redirect_to bookings_path
  end
end

app/views/bookings/index.html.haml
.panel.panel-default
  .panel-heading.clearfix
    %h2.panel-title.pull-left
      =t(:bookings)
    .pull-right
      .btn-group
        %a.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          =@filtered_by
          %span.caret
        %ul.dropdown-menu
          %li=link_to 'Pendientes', bookings_path
          %li=link_to 'Confirmadas', approved_bookings_path
          %li=link_to 'Anuladas', canceled_bookings_path
  %table.table.table-striped.table-hover
    %tr
      %th Lugar
      %th Fecha
      %th Cliente
      %th Servicios
      %th Duración estimada
      %th
    - @bookings.try(:each) do |booking|
      %tr
        %td(style='word-wrap: break-word')
          %span
            %i.fa.fa-building-o
            =booking.place.name
        %td(style='white-space: nowrap')
          %span
            %i.fa.fa-calendar
            =booking.date.strftime('%Y-%m-%d %I:%M %P')
        %td(style='word-wrap: break-word')
          %span
            %i.fa.fa-user
            =booking_user_full_name(booking.user)
          %br
          %span
            %i.fa.fa-phone
            =booking.user.phone_number
        %td(style='word-wrap: break-word')
          %ul
            - booking.booked_services.each do |service|
              %li
                %b=service.service_name
                %br
                %span
                  %i.fa.fa-clock-o
                  =service_time_in_words(service.service_duration)
        %td(style='white-space: nowrap')
          %span
            %i.fa.fa-clock-o
            =booked_services_duration(booking.booked_services)
        %td(style='min-width: 120px')
          .btn-group
            - if booking.confirmed_at.nil? && booking.canceled_at.nil?
              =link_to approve_booking_path(booking), class: 'btn btn-large btn-success', method: :post do
                %i.fa.fa-check
              =link_to  discard_booking_path(booking), class: 'btn btn-large btn-danger', method: :post do
                %i.fa.fa-trash