config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :places, only: [:index, :show] do
        member do
          get 'bookings/:on_day' => 'places#bookings', as: :bookings
        end
      end

      resources :bookings, only: [:create, :index]
      resources :ratings, only: [:create] do
        get 'current/:place_id/:user_id', :on => :collection, :action => 'show'
      end

      post 'login' => 'users#login', as: 'login'
      post 'logout' => 'users#logout', as: 'logout'
      post 'signup' => 'users#signup', as: 'signup'
      post '/users/profile' => 'users#update', as: 'update'
    end
  end

  devise_for :users, controllers: { sessions: 'sessions', passwords: 'passwords' }

  scope '/admin' do
    devise_for :admins

    resources :users
    resources :places, concerns: :paginatable do
      with_options except: [:index, :show] do |list_except|
        list_except.resources :schedules
        list_except.resources :services
      end
    end

    resources :bookings, only: [:index] do
      member do
        post 'approve'
        post 'discard'
      end

      collection do
        get 'canceled' => 'bookings#canceled', as: :canceled
        get 'approved' => 'bookings#approved', as: :approved
      end
    end
  end

  mount PostgresqlLoStreamer::Engine => '/lo'

  root 'places#index'
end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  address        :string(255)
#  description    :string(255)
#  mobile_phone   :string(10)
#  land_line      :string(10)
#  created_at     :datetime
#  updated_at     :datetime
#  photo1         :integer
#  photo2         :integer
#  photo3         :integer
#  rating_average :decimal(, )
#

##
# Esta clase representa los lugares
# @author Jenny Lopez
class Place < ActiveRecord::Base
  # Tiene varios horarios
  has_many :schedules, dependent: :destroy

  # Tiene varios servicios
  has_many :services, dependent: :destroy

  # Tiene varios servicios
  has_many :bookings, dependent: :destroy

  # Tiene varias calificacones
  has_many :ratings

  # Configuración de carrierwave para la subida de imágenes de lugares
  mount_uploader :photo1, PlacePhotoUploader
  mount_uploader :photo2, PlacePhotoUploader
  mount_uploader :photo3, PlacePhotoUploader

  # Cantidad reulstados por página
  paginates_per 10

  default_scope -> { order('places.name ASC') }

  # Obtiene la lista de lugares que tienen asociados servicios y horarios
  scope :completed, (lambda do
    includes(:services, :schedules)
    .where.not(services: { id: nil }, schedules: { id: nil })
  end)

  def batch_create_schedules(schedule_params)
    schedules.create!(schedule_params)
  rescue
    []
  end
end

app/controllers/api/v1/places_controller.rb
module API
  module V1

    BookingStruct = Struct.new(:date, :available, :booking_id, :duration, :ok)

    ##
    # Esta clase representa un punto de montaje en el api para
    # enviar los lugares disponibles
    class PlacesController < API::V1::BaseController
      doorkeeper_for :all
      before_action :set_place, only: [:show, :bookings]

      ##
      # Listado de lugares
      # GET /api/v1/places
      def index
        @places = Place.completed
      end

      ##
      # Un lugar en específico
      # GET /api/v1/places/:id
      def show
        render partial: 'place', locals: { place: @place }
      end

      ##
      # Reservas de un lugar
      # GET /api/v1/places/:id/bookings/:on_day
      def bookings
        date = Date.parse(place_params[:on_day]).beginning_of_day

        starts = date.advance(hours: 7).to_i
        ends = date.advance(hours: 19).to_i

        bookings_on_day = @place.bookings.on_day(date)

        @bookings = (starts..ends).step(1.hour).to_a.map do |time|
          BookingStruct.new(Time.at(time), true)
        end

        @bookings.each_with_index do |time, index|
          next if !@bookings[index].ok.nil?

          booking = bookings_on_day.detect {|b| b.date ==  time.date}
          services = booking.booked_services rescue nil
          duration = DateTime.parse(services.sum(:service_duration)) if services

          if !booking.nil?
            mark_booking_unavailable(booking, duration, index)
            if duration.hour > 0 && duration.min > 0
              (1..duration.hour).each do |h|
                mark_booking_unavailable(booking, duration, index+h)
              end
            end
          end
        end
      end

      private

      def set_place
        @place = Place.find(params[:id])
      end

      def place_params
        params.permit(:on_day)
      end

      def mark_booking_unavailable(booking, duration, index)
        return if index > @bookings.length

        @bookings[index].available = false
        @bookings[index].booking_id = booking.id
        @bookings[index].duration = duration
        @bookings[index].ok = true
      end
    end
  end
end

app/controllers/places_controller.rb
##
# Esta clase representa el controlador encargado de realizar las operaciones
# CRUD de un lugar
class PlacesController < ApplicationController
  before_action :set_place, only: [:edit, :destroy]

  def index
    @places = Place.page(params[:page])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = t(:place_created)
      redirect_to edit_place_path(@place)
    else
      render action: 'new'
    end
  end

  def edit
    @schedules = @place.schedules.group_by(&:day_of_week)
    @services = @place.services.group_by(&:kind)
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      flash[:success] = t(:place_updated)
      redirect_to edit_place_path(@place)
    else
      render 'edit'
    end
  end

  def destroy
    @place.destroy
    redirect_to places_path
  end

  private

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(
      :name,
      :address,
      :description,
      :mobile_phone,
      :land_line,
      :photo1,
      :photo2,
      :photo3
    )
  end
end

app/views/places/_detail.html.haml
.panel.panel-default
  .panel-heading.clearfix
    %h3.panel-title.pull-left=@place.name
    %a.btn.btn-primary.pull-right{:href => edit_place_path(@place)}
      %i.fa.fa-pencil
      %span=t(:edit)

app/views/places/_form.html.haml
=simple_form_for @place do |f|
  %table.table
    %tr
      %td
        =f.label :name, t('simple_form.labels.place.name')
        .list-group-item-heading=f.input_field :name, class: 'form-control'
      %td
        =f.label :address, t('simple_form.labels.place.address')
        .list-group-item-heading=f.input_field :address, class: 'form-control'
    %tr
      %td
        =f.label :land_line, t('simple_form.labels.place.land_line')
        .list-group-item-heading=f.input_field :land_line, class: 'form-control'
      %td
        =f.label :mobile_phone, t('simple_form.labels.place.mobile_phone')
        .list-group-item-heading=f.input_field :mobile_phone, class: 'form-control'
    %tr
      %td(colspan=2)
        =f.label :description, t('simple_form.labels.place.description')
        .list-group-item-heading=f.input_field :description, class: 'form-control', as: :text
  .row
    .col-sm-4
      .list-group-item
        =f.label :photo1, t('simple_form.labels.place.photo1')
        .list-group-item-heading=f.input_field :photo1, as: :file, class: 'form-control'
        =link_to lo_image_url(@place.photo1), target: '_new' do
          =image_tag lo_image_url(@place.photo1), style: 'width: 100%', class: 'thumbnail'
    .col-sm-4
      .list-group-item
        =f.label :photo2, t('simple_form.labels.place.photo2')
        .list-group-item-heading=f.input_field :photo2, as: :file, class: 'form-control'
        =link_to lo_image_url(@place.photo2), target: '_new' do
          =image_tag lo_image_url(@place.photo2), style: 'width: 100%', class: 'thumbnail'
    .col-sm-4
      .list-group-item
        =f.label :photo3, t('simple_form.labels.place.photo3')
        .list-group-item-heading=f.input_field :photo3, as: :file, class: 'form-control'
        =link_to lo_image_url(@place.photo3), target: '_new' do
          =image_tag lo_image_url(@place.photo3), style: 'width: 100%', class: 'thumbnail'
  .list-group-item
    .list-group-item-heading
      =f.button :submit, 'Enviar', class: 'btn-primary'

app/views/places/_list.html.haml
.panel.panel-default
  .panel-body
    %form.form-inline(role="form")
      .form-group
        / %input.form-control{placeholder: t(:search_place), type: "text"}
        / %a.btn.btn-info{href: new_place_path}
        /   %i.fa.fa-search
        /   %span=t(:search)
        %a.btn.btn-primary{href: new_place_path}
          %i.fa.fa-plus
          %span=t(:add)
  .list-group
    - @places.each do |place|
      %a.list-group-item{href: edit_place_path(place), class: selected_index_item_class(place)}
        %i.fa.fa-3x.fa-building-o.pull-left
        %h5.list-group-item-heading
          ="#{place.name}, #{place.address}"
        %p.list-group-item-text
          =place.description
          ="#{place.land_line} - #{place.mobile_phone}"


=paginate @places

app/views/places/_schedule.html.haml
.panel.panel-default
  .panel-heading.clearfix
    %h3.panel-title.pull-left=t(:schedule)
    .btn-group.pull-right
      =link_to new_place_schedule_path(@place), class: 'btn btn-primary' do
        %i.fa.fa-plus
        %span=t(:add)
  .row
    - Schedule::DAYS.each do |day_name, day_number|
      .col-sm-4
        %table.table.table-hover
          %tr
            %th=t(day_name.downcase)
          - @schedules[day_number].try(:each) do |hour|
            %tr
              %td=link_to time_range(hour), edit_place_schedule_path(@place, id: hour[:id])

app/views/places/_services.html.haml
.panel.panel-default
  .panel-heading.clearfix
    %h3.panel-title.pull-left=t(:services)
    .btn-group.pull-right
      =link_to new_place_service_path(@place), class: 'btn btn-primary' do
        %i.fa.fa-plus
        %span=t(:add)
  .row
    - Service.kinds.keys.each do |kind|
      .col-sm-4
        %table.table.table-hover
          %tr
            %th=t(kind.to_s.downcase)
          - !@services[kind].nil? and @services[kind].each do |service|
            %tr
              %td=link_to service_detail(service), edit_place_service_path(@place, service)

app/views/places/edit.html.haml
%ul.nav.nav-tabs{:role => "tablist"}
  %li.active{:role => "presentation"}
    %a{"data-toggle" => "tab", :href => "#place", :role => "tab"} Inicio
  %li{:role => "presentation"}
    %a{"data-toggle" => "tab", :href => "#services", :role => "tab"} Servicios
  %li{:role => "presentation"}
    %a{"data-toggle" => "tab", :href => "#horarios", :role => "tab"} Horario
.tab-content
  #place.tab-pane.active{:role => "tabpanel"}
    .panel.panel-default
      .panel-heading.clearfix
        %h3.panel-title.pull-left Información del lugar
        .btn-group.pull-right
          =link_to places_path, class: 'btn btn-info' do
            %i.fa.fa-arrow-left
            %span=t(:back)
          =link_to place_path(@place), class: 'btn btn-danger', data: {confirm: t(:delete_place_confirm)}, method: :delete do
            %i.fa.fa-trash
            %span=t(:delete)
      .list-group
        =render 'form'
  #services.tab-pane{:role => "tabpanel"}
    =render 'services'
  #horarios.tab-pane{:role => "tabpanel"}
    =render 'schedule'

app/views/places/index.html.haml
.row
  #list.col-sm-12{"data-title" => t(:places)}
    =render 'list'

app/views/places/new.html.haml
.panel.panel-default
  .panel-heading.clearfix
    %h3.panel-title.pull-left
      =t(:new)
    .btn-group.pull-right
      %a.btn.btn-info{:href => places_path}
        %i.fa.fa-arrow-left
        %span=t(:back)
  .list-group
    =render 'form'