config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :places, only: [:index, :show] do
        member do
          get 'bookings/:on_day' => 'places#bookings', as: :bookings
        end
      end

      resources :bookings, only: [:create, :index]
      resources :ratings, only: [:create] do
        get 'current/:place_id/:user_id', :on => :collection, :action => 'show'
      end

      post 'login' => 'users#login', as: 'login'
      post 'logout' => 'users#logout', as: 'logout'
      post 'signup' => 'users#signup', as: 'signup'
      post '/users/profile' => 'users#update', as: 'update'
    end
  end

  devise_for :users, controllers: { sessions: 'sessions', passwords: 'passwords' }

  scope '/admin' do
    devise_for :admins

    resources :users
    resources :places, concerns: :paginatable do
      with_options except: [:index, :show] do |list_except|
        list_except.resources :schedules
        list_except.resources :services
      end
    end

    resources :bookings, only: [:index] do
      member do
        post 'approve'
        post 'discard'
      end

      collection do
        get 'canceled' => 'bookings#canceled', as: :canceled
        get 'approved' => 'bookings#approved', as: :approved
      end
    end
  end

  mount PostgresqlLoStreamer::Engine => '/lo'

  root 'places#index'
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/"} Mi Peluquería
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: ('active' if current_page?(places_path))}
          = link_to places_path, class: '' do
            %i.fa.fa-building-o
            =t(:places)
        %li{class: ('active' if current_page?(bookings_path))}
          = link_to bookings_path, class: '' do
            %i.fa.fa-calendar
            =t(:bookings)
            %span.badge.badge-success
              =pending_confirm_count
        %li{class: ('active' if current_page?(users_path))}
          = link_to users_path, class: '' do
            %i.fa.fa-users
            =t(:users)
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to destroy_admin_session_path, method: :delete, class: '' do
            %i.fa.fa-user
            =t(:sign_out)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', :name => 'viewport'}
    %meta{:name => "google", :value => "notranslate"}
    %title Backend
    =stylesheet_link_tag    'application', media: 'all'
    =javascript_include_tag 'application'
    =csrf_meta_tags
  %body
    = render partial: 'layouts/header' if admin_signed_in?
    .container
      - flash.each do |name, msg|
        .alert{:class => "alert-#{alert_css_class(name)}", :role => 'alert'}=msg
      =yield